GET https://www.api.wilgner.com.br/lindeiros/user 
Content-Type: application/json; charset=utf-8;
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYWY3YzU4OTgtZjc1My00MmY0LThkNjEtNDQ3M2RlNTg1MWQ0In0.K8_Lxv7ddi3IxREVJ4eTcJwkLVAbW96kHW04rkx3w78


